# Generated by Django 5.1.7 on 2025-05-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todolist', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";',
                ("""
                    CREATE TABLE todo (
                        id UUID primary key default uuid_generate_v4(),
                        created_at date default now(),
                        name text
                    );
                """)
            ],

            reverse_sql=[
                'DROP EXTENSION IF EXISTS "uuid-ossp";',
                ("""
                    DROP TABLE IF EXISTS todo;
                """)
            ]
        )
    ]
